# SAGE build/verify entry points. `make reproduce` is a gate condition:
# every domain-gate artifact must regenerate from fixed seeds.

.PHONY: sync test lint types gates gates-check reproduce reproduce-fast dashboard docs clean

sync:
	uv sync --all-packages

test:
	uv run pytest -q

lint:
	uv run ruff check .
	uv run ruff format --check .

types:
	uv run mypy packages/strataq/strataq packages/strataq-bench/strataq_bench

gates:
	uv run python gates/run_gates.py --all

gates-check:
	uv run python gates/run_gates.py --check

# Regenerate every gate artifact from fixed seeds (config/base.yaml seed policy).
# Stage 0 has no domain artifacts; experiments append their regeneration targets
# here as units close — a gate whose artifact is not regenerated by this target
# is not green.
reproduce: reproduce-fast
	uv run python -m experiments.reciprocity_calibration
	uv run python -m experiments.dynamics_calibration
	uv run python -m experiments.solver_validation
	uv run python -m experiments.blotto_calibration
	uv run python -m experiments.congestion_calibration
	uv run python -m experiments.estimator_validation
	uv run python -m experiments.estimator_recovery
	uv run python -m experiments.electricity_reading
	uv run python -m experiments.frontier
	uv run python -m experiments.pricing_reading
	uv run python -m experiments.protocol_reading
	uv run python -m experiments.bayes_reading
	uv run python -m experiments.toolkit_verdicts

# Fast subset: what `main` must always pass (CI runs this on every merge).
reproduce-fast:
	uv run pytest -q
	uv run python gates/run_gates.py --check

dashboard:
	uv run python docs/progress/generate.py

docs:
	uv run mkdocs build --strict

clean:
	rm -rf .venv dist build .pytest_cache .mypy_cache .ruff_cache
