"""Golden files for the client-side math module (apps/web/lib/qre.ts).

The hybrid-compute rule: the browser may compute small interactions itself,
but only against goldens generated by the gated library — this script is the
tether. Regenerate with:

    uv run python apps/web/scripts/make_goldens.py

CI (and the web test script) fail if lib/qre.ts disagrees with these numbers.
"""

from __future__ import annotations

import json
from pathlib import Path

import jax.numpy as jnp
from strataq.core.solve.fixedpoint import logit_qre
from strataq.finite.games.library import (
    coordination,
    matching_pennies,
    rock_paper_scissors,
)
from strataq.finite.games.tensor import DenseTensorGame

OUT = Path(__file__).resolve().parents[1] / "lib" / "goldens.json"

ASYM = DenseTensorGame(
    (
        jnp.array([[3.0, 0.0, 1.5], [1.0, 2.0, 0.5], [0.0, 1.0, 2.5]]),
        jnp.array([[2.0, 1.0, 0.0], [0.5, 3.0, 1.0], [1.5, 0.0, 2.0]]),
    )
)

CASES = {
    "rps": rock_paper_scissors(),
    "matching_pennies": matching_pennies(),
    "coordination_2x3": coordination(2, 3, bonus=2.0),
    "asym_3x3": ASYM,
}

LAMBDAS = [0.3, 1.2, 4.0]


def main() -> None:
    goldens: dict = {"cases": {}}
    for name, game in CASES.items():
        payoffs = [u.tolist() for u in game.payoffs]
        solves = []
        for lam in LAMBDAS:
            point = logit_qre(game, lam)
            solves.append(
                {
                    "lam": lam,
                    "sigma": [s.tolist() for s in point.sigma],
                    "residual": float(point.residual),
                }
            )
        goldens["cases"][name] = {"payoffs": payoffs, "solves": solves}
    OUT.write_text(json.dumps(goldens, indent=1) + "\n")
    print(f"wrote {OUT} ({len(CASES)} cases x {len(LAMBDAS)} lambdas)")


if __name__ == "__main__":
    main()
