"""Golden files for the client-side math module (apps/web/lib/qre.ts).

The hybrid-compute rule: the browser may compute small interactions itself,
but only against goldens generated by the gated library — this script is the
tether. Regenerate with:

    uv run python apps/web/scripts/make_goldens.py

CI (and the web test script) fail if lib/qre.ts disagrees with these numbers.
"""

from __future__ import annotations

import json
from pathlib import Path

import jax.numpy as jnp
from strataq.core.solve.fixedpoint import logit_qre
from strataq.finite.games.library import (
    coordination,
    matching_pennies,
    rock_paper_scissors,
)
from strataq.finite.games.tensor import DenseTensorGame

OUT = Path(__file__).resolve().parents[1] / "lib" / "goldens.json"

ASYM = DenseTensorGame(
    (
        jnp.array([[3.0, 0.0, 1.5], [1.0, 2.0, 0.5], [0.0, 1.0, 2.5]]),
        jnp.array([[2.0, 1.0, 0.0], [0.5, 3.0, 1.0], [1.5, 0.0, 2.0]]),
    )
)

CASES = {
    "rps": rock_paper_scissors(),
    "matching_pennies": matching_pennies(),
    "coordination_2x3": coordination(2, 3, bonus=2.0),
    "asym_3x3": ASYM,
}

LAMBDAS = [0.3, 1.2, 4.0]


def _softmax(v, lam):
    import jax.nn

    return jax.nn.softmax(lam * jnp.asarray(v, dtype=jnp.float64))


def primitives() -> dict:
    """References for every client-side primitive, from the library's stack."""
    vals = [102.0, 108.0, 115.0, 113.0, 104.0]
    rps = jnp.array([[0.0, -1.0, 1.0], [1.0, 0.0, -1.0], [-1.0, 1.0, 0.0]])
    coord = jnp.array([[2.0, 0.0, 0.0], [0.0, 2.0, 0.0], [0.0, 0.0, 2.0]])

    softmax_cases = []
    for lam in [0.05, 0.3, 2.0]:
        pr = _softmax(vals, lam)
        h = float(-jnp.sum(jnp.where(pr > 0, pr * jnp.log(pr), 0.0)))
        softmax_cases.append({"values": vals, "lam": lam, "probs": pr.tolist(), "entropy": h})

    flow_cases = []
    for xx in ([0.5, 0.3, 0.2], [0.2, 0.2, 0.6], [1 / 3, 1 / 3, 1 / 3]):
        for lam in [0.8, 2.0]:
            f = _softmax(rps @ jnp.asarray(xx), lam) - jnp.asarray(xx)
            flow_cases.append({"u": rps.tolist(), "x": list(xx), "lam": lam, "flow": f.tolist()})

    # symmetric single-population fixed point of coordination at lam=2 seeded
    # asymmetrically -> converges to the basin's rest point; used to check the
    # client trajectory integrator lands where the field says it must.
    y = jnp.array([0.6, 0.25, 0.15])
    for _ in range(20000):
        y = 0.5 * y + 0.5 * _softmax(coord @ y, 2.0)
    argmax_cases = [
        {"values": [1.0, 2.0, 2.0], "mix": [0.0, 0.5, 0.5]},
        {"values": [3.0, 1.0, 0.0], "mix": [1.0, 0.0, 0.0]},
    ]
    u2 = ASYM.payoffs[1]
    row_mix = [0.2, 0.5, 0.3]
    epc = (jnp.asarray(row_mix) @ u2).tolist()
    return {
        "softmax": softmax_cases,
        "logit_flow": flow_cases,
        "coordination_rest_point": {
            "u": coord.tolist(),
            "lam": 2.0,
            "seed": [0.6, 0.25, 0.15],
            "rest": y.tolist(),
        },
        "argmax": argmax_cases,
        "expected_payoffs_col": {"u2": u2.tolist(), "row_mix": row_mix, "out": epc},
    }


def main() -> None:
    goldens: dict = {"cases": {}, "primitives": primitives()}
    for name, game in CASES.items():
        payoffs = [u.tolist() for u in game.payoffs]
        solves = []
        for lam in LAMBDAS:
            point = logit_qre(game, lam)
            solves.append(
                {
                    "lam": lam,
                    "sigma": [s.tolist() for s in point.sigma],
                    "residual": float(point.residual),
                }
            )
        goldens["cases"][name] = {"payoffs": payoffs, "solves": solves}
    OUT.write_text(json.dumps(goldens, indent=1) + "\n")
    print(f"wrote {OUT} ({len(CASES)} cases x {len(LAMBDAS)} lambdas)")


if __name__ == "__main__":
    main()
