/* Client-side game math for the explorable panels.
 *
 * HYBRID-COMPUTE RULE: this module exists so sliders feel instant (<16ms),
 * but it is tethered to the gated library — lib/goldens.json is generated by
 * strataq (scripts/make_goldens.py) and scripts/test-qre.mjs fails the build
 * if this implementation drifts. Heavy or authoritative readings (branch
 * traces, exact dynamics, χ/ℛ, real networks) always come from the deployed
 * float64 solver via /api and carry a provenance badge in the UI.
 *
 * Scope: 2-player dense games, small action counts. Nothing here is used for
 * a published number.
 */

export type Matrix = number[][]; // u[i][j] — row player action i, column player action j

export interface TwoPlayerGame {
  u1: Matrix; // row player payoffs
  u2: Matrix; // column player payoffs (same shape)
}

export function softmax(values: number[], lam: number): number[] {
  const scaled = values.map((v) => lam * v);
  const m = Math.max(...scaled);
  const w = scaled.map((v) => Math.exp(v - m));
  const z = w.reduce((a, b) => a + b, 0);
  return w.map((v) => v / z);
}

/** Expected payoff of each row-player action against a column mix. */
export function expectedPayoffsRow(u1: Matrix, colMix: number[]): number[] {
  return u1.map((row) => row.reduce((acc, v, j) => acc + v * colMix[j], 0));
}

/** Expected payoff of each column-player action against a row mix. */
export function expectedPayoffsCol(u2: Matrix, rowMix: number[]): number[] {
  const nCols = u2[0].length;
  const out = new Array(nCols).fill(0);
  for (let j = 0; j < nCols; j++) {
    for (let i = 0; i < u2.length; i++) out[j] += u2[i][j] * rowMix[i];
  }
  return out;
}

export interface QRESolution {
  sigma1: number[];
  sigma2: number[];
  residual: number;
  iterations: number;
  converged: boolean;
}

/** Damped logit QRE iteration — mirrors strataq.core.solve.fixedpoint. */
export function solveQRE(
  game: TwoPlayerGame,
  lam: number,
  opts: { damping?: number; tol?: number; maxIter?: number } = {},
): QRESolution {
  const { damping = 0.5, tol = 1e-10, maxIter = 4000 } = opts;
  const n1 = game.u1.length;
  const n2 = game.u1[0].length;
  let s1 = new Array(n1).fill(1 / n1);
  let s2 = new Array(n2).fill(1 / n2);
  let residual = Infinity;
  let it = 0;
  for (; it < maxIter; it++) {
    const b1 = softmax(expectedPayoffsRow(game.u1, s2), lam);
    const b2 = softmax(expectedPayoffsCol(game.u2, s1), lam);
    residual = Math.max(
      ...b1.map((v, i) => Math.abs(v - s1[i])),
      ...b2.map((v, j) => Math.abs(v - s2[j])),
    );
    s1 = s1.map((v, i) => v + damping * (b1[i] - v));
    s2 = s2.map((v, j) => v + damping * (b2[j] - v));
    if (residual < tol) break;
  }
  return { sigma1: s1, sigma2: s2, residual, iterations: it, converged: residual < tol };
}

/** Best-response (Nash-limit) mix: argmax with ties split uniformly. */
export function argmaxMix(values: number[]): number[] {
  const m = Math.max(...values);
  const winners = values.map((v) => (Math.abs(v - m) < 1e-12 ? 1 : 0));
  const k = winners.reduce((a, b) => a + b, 0);
  return winners.map((w) => w / k);
}

/** Shannon entropy in nats. */
export function entropy(p: number[]): number {
  return -p.reduce((acc, v) => (v > 1e-300 ? acc + v * Math.log(v) : acc), 0);
}

/**
 * Single-population logit dynamics vector field on the simplex for a
 * symmetric game (used by the simplex phase portrait):
 *   dx/dt = softmax(λ · U x) − x.
 */
export function logitFlow(u: Matrix, x: number[], lam: number): number[] {
  const payoff = u.map((row) => row.reduce((acc, v, j) => acc + v * x[j], 0));
  const target = softmax(payoff, lam);
  return target.map((t, i) => t - x[i]);
}

/** Integrate the logit flow from a seed point (simple RK2, fixed step). */
export function logitTrajectory(
  u: Matrix,
  x0: number[],
  lam: number,
  opts: { dt?: number; steps?: number } = {},
): number[][] {
  const { dt = 0.05, steps = 400 } = opts;
  let x = [...x0];
  const path = [x];
  for (let s = 0; s < steps; s++) {
    const k1 = logitFlow(u, x, lam);
    const mid = x.map((v, i) => v + 0.5 * dt * k1[i]);
    const k2 = logitFlow(u, normalizeSimplex(mid), lam);
    x = normalizeSimplex(x.map((v, i) => v + dt * k2[i]));
    path.push(x);
  }
  return path;
}

function normalizeSimplex(x: number[]): number[] {
  const clipped = x.map((v) => Math.max(v, 1e-12));
  const z = clipped.reduce((a, b) => a + b, 0);
  return clipped.map((v) => v / z);
}

/** Barycentric → 2D coordinates for an equilateral simplex drawing. */
export function simplexToXY(p: number[]): [number, number] {
  // vertices: A=(0,0) action0, B=(1,0) action1, C=(0.5, sqrt(3)/2) action2
  const x = p[1] + 0.5 * p[2];
  const y = (Math.sqrt(3) / 2) * p[2];
  return [x, y];
}
