"""Synthesise game families at target harmonic fraction α.

Families are generated by projecting and re-mixing components — never by
perturbing a Jacobian (the skew part of a Jacobian is coordinate-dependent and
generally not integrable; PROGRAMME v3 §1.2 caveat). Because the potential and
harmonic components are orthogonal, mixing unit-norm components at weights
(1−α, α) yields a game whose measured α is exactly the target.

References
----------
PROGRAMME v3 §3.2 (canonical α; families by projection and re-mixing).
Tier: exact construction on top of K5.
"""

from __future__ import annotations

from collections.abc import Sequence

import jax.numpy as jnp

from strataq.finite.decompose.hodge import hodge_decompose
from strataq.finite.games.tensor import DenseTensorGame


def _unit(payoffs: tuple[jnp.ndarray, ...]) -> tuple[jnp.ndarray, ...]:
    norm = jnp.sqrt(sum(jnp.sum(u**2) for u in payoffs))
    if float(norm) == 0.0:
        raise ValueError("component has zero norm; cannot normalise")
    return tuple(u / norm for u in payoffs)


def make_family(
    potential_source: DenseTensorGame,
    harmonic_source: DenseTensorGame,
    alphas: Sequence[float],
    *,
    scale: float = 1.0,
) -> list[DenseTensorGame]:
    """Games with α exactly as requested, mixing the sources' components.

    The potential component of ``potential_source`` and the harmonic component
    of ``harmonic_source`` are extracted, unit-normalised, and mixed as
    ((1−α)·P̂ + α·Ĥ)·scale. Shapes must match.
    """
    if potential_source.num_actions != harmonic_source.num_actions:
        raise ValueError("sources must share an action-space shape")
    p_hat = _unit(hodge_decompose(potential_source).potential.payoffs)
    h_hat = _unit(hodge_decompose(harmonic_source).harmonic.payoffs)

    family = []
    for a in alphas:
        if not 0.0 <= a <= 1.0:
            raise ValueError(f"alpha {a} outside [0, 1]")
        payoffs = tuple(scale * ((1.0 - a) * p + a * h) for p, h in zip(p_hat, h_hat, strict=True))
        family.append(DenseTensorGame(payoffs))
    return family
